version: '3.8'

services:
  db-curso:
    image: postgres
    container_name: meu_postgres_curso
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgresql-product-fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: product_api_app
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql+asyncpg://root:root@db-curso:5432/postgresql-product-fastapi"
    ports:
      - "8000:8000"
    depends_on:
      - db-curso
    networks:
      - default

volumes:
  postgres_data: