"""Adjust column names from portuguese to english

Revision ID: 6ac129575fe3
Revises: bbf343fc73c8
Create Date: 2024-11-04 20:52:48.798613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac129575fe3'
down_revision: Union[str, None] = 'bbf343fc73c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('produtos', sa.Column('description', sa.String(length=256), nullable=True))
    op.drop_column('produtos', 'preco')
    op.drop_column('produtos', 'descricao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('descricao', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('produtos', sa.Column('preco', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('produtos', 'description')
    op.drop_column('produtos', 'price')
    # ### end Alembic commands ###
